apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: xss-bot
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
  # You can allow the bot to connect to other challenges internally.
  # This can be useful during testing so that you don't have to make your
  # challenge public.
  # The challenge will be reachable at $name.default.svc.cluster.local or
  # simply at $name with the default k8s search list.
  #allowConnectTo:
  #  - otherchallenge
  horizontalPodAutoscalerSpec:
    maxReplicas: 10
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: 'challenge'
            resources:
              requests:
                memory: "2048Mi"
                cpu: "1000m"
