# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: d8
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: eu.gcr.io/gctf-2022/d8-healthcheck:158f57a4fc64648c4389faf6e30bc50194f489f3132ab6b9f9fea0dad01fd982
  image: eu.gcr.io/gctf-2022/d8-challenge:5821467b3f79317798b961fa94085f697f405c4a675fafb0bbba974e00c1673b
  horizontalPodAutoscalerSpec:
    maxReplicas: 2
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: 'challenge'
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
