apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: electric-mayhem-pqc
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: eu.gcr.io/gctf-2022/electric-mayhem-pqc-healthcheck:7dbea7f953804837ae1e758b592c809520afaa009f2fd78dac8aedad5669a61f
  image: eu.gcr.io/gctf-2022/electric-mayhem-pqc-challenge:184158299dc16ded48d40645d51365a447998689cdd36742b7883160403fd4d2
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: 'challenge'
            resources:
              requests:
                memory: "4Gi"
                cpu: "2"
