apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: apache-others
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
    - protocol: "HTTPS"
      targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
  horizontalPodAutoscalerSpec:
    maxReplicas: 10
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: 'challenge'
            resources:
              requests:
                memory: "8Gi"
                cpu: "4000m"
