apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: pcivault
spec:
  deployed: true
  powDifficultySeconds: 60
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: kvm-volume
                mountPath: /dev/kvm
            securityContext:
              privileged: true
        volumes:
          - name: kvm-volume
            hostPath:
              path: /dev/kvm
        nodeSelector:
          dedicated: kvm
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kvm"
            effect: "NoExecute"
