apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: treebox
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: eu.gcr.io/gctf-2022/treebox-healthcheck:ed2f4947c00dc182e7f80eefe545958178317510ab9d0d2804d7f867397bec44
  image: eu.gcr.io/gctf-2022/treebox-challenge:e356ba6b406c15bf9f29f4895b6afa096a3a4069a7e3a929d50c813b59e56b0a
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: 'challenge'
            resources:
              requests:
                memory: "2Gi"
                cpu: "1"
