name: ctf_story
description: A crypto challenge in Google CTF 2021.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  crclib:
    git:
      url: https://github.com/google/crclib.dart
      ref: main
