apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: filestore
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
