apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: sendbox
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: 'challenge'
            resources:
              requests:
                memory: "2Gi"
                cpu: "1"
