apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: segfault-labyrinth
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: eu.gcr.io/gctf-2022/segfault-labyrinth-healthcheck:8be565097005d65515fe60830080781f980f15a5c37b23ccb095f8fe1452242e
  image: eu.gcr.io/gctf-2022/segfault-labyrinth-challenge:3b0e50777c5be5c9e94d56192d4e16ee4ff122fd1d19f0adcbd79d4632c1cff1
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 2
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: 'challenge'
            resources:
              requests:
                memory: "2Gi"
                cpu: "1"
